/**
 * Embeds data/catalog/*.json into src/generated/data.ts so the built package
 * is self-contained (no runtime file reads, no JSON import attributes). The
 * output is rewritten only when it changes, which keeps incremental builds and
 * turbo caches warm. `data/catalog/**` is a turbo global dependency, so editing
 * the JSON invalidates every task that consumes this package.
 */
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = fileURLToPath(new URL("../", import.meta.url));
const catalogDir = join(packageRoot, "../../data/catalog");
const outputDir = join(packageRoot, "src/generated");
const outputFile = join(outputDir, "data.ts");

const files = {};
for (const name of (await readdir(catalogDir)).sort()) {
  if (!name.endsWith(".json")) continue;
  files[name.replace(/\.json$/, "")] = JSON.parse(await readFile(join(catalogDir, name), "utf8"));
}
if (Object.keys(files).length === 0) throw new Error(`No catalog files found in ${catalogDir}`);

const source = [
  "/* eslint-disable */",
  "// Generated by scripts/generate.mjs from data/catalog. Do not edit by hand.",
  `export const catalogSource: string = ${JSON.stringify(JSON.stringify(files))};`,
  "",
].join("\n");

await mkdir(outputDir, { recursive: true });
let current = null;
try { current = await readFile(outputFile, "utf8"); } catch { /* first run */ }
if (current !== source) await writeFile(outputFile, source);
